In [111]:
import pandas as pd
import numpy as np

In [112]:
# This is the data the gis team gave us, manipulated to modify date columns
VDOTcarcass = pd.read_csv('VDOTCarcass.csv')
# This is the original data from the VDOT Carcass Removal Map
Wildlifecarcass = pd.read_csv('Wildlife_Carcass_Removal_Tracking_5676419084963296149.csv')

In [113]:
Wildlifecarcass.head()

,ObjectID,GlobalID,Date and Pickup Time,Deer and Bear Removal,Other wildlife types,Route Name and Direction,Latitude_d,Longitude_d,County,District,Residency,x,y
0,83,ac10868c-9c94-444f-bb95-36b03bfd84a0,5/18/2021 12:43:01 PM,Deer,NaN,I-81S,37.835462,-79.370354,Rockbridge,Staunton,Lexington,-79.370354,37.835462
1,84,f529067b-0a14-401a-b0f7-b1701e771f4a,5/18/2021 2:15:55 PM,NaN,Coyote,I-81S,37.713655,-79.450178,Rockbridge,Staunton,Lexington,-79.450178,37.713655
2,85,d966d639-1944-4973-ac57-ad782bca5f38,5/18/2021 2:23:35 PM,NaN,Groundhog,I-81S,37.714697,-79.448655,Rockbridge,Staunton,Lexington,-79.448655,37.714697
3,86,7f5ea06a-c97d-4947-8e9e-aa5a14ca919f,5/18/2021 2:52:00 PM,Deer,NaN,I-81S,37.641463,-79.561258,Rockbridge,Staunton,Lexington,-79.561258,37.641463
4,88,2706ba75-9f2c-49a6-8eee-a7a4d02b42f1,5/18/2021 3:33:52 PM,Deer,NaN,I-81N,37.758094,-79.408782,Rockbridge,Staunton,Lexington,-79.408782,37.758094

In [114]:
VDOTcarcass.head()

,fid,ObjectID,GlobalID,StartTime,Date,Year,MonthName,MonthNumber,DOWName,DOWNumber,DOMNumber,Wildlife,WildlifeOther,Route,Jurisdiction,District,Residency,x,y
0,1,83,{AC10868C-9C94-444F-BB95-36B03BFD84A0},5/18/2021 12:43:01 PM,2021-05-18,2021,May,5,Tuesday,3,18,Deer,NaN,I-81S,Rockbridge,Staunton,Lexington,-79.370354,37.835462
1,2,84,{F529067B-0A14-401A-B0F7-B1701E771F4A},5/18/2021 2:15:55 PM,2021-05-18,2021,May,5,Tuesday,3,18,NaN,Coyote,I-81S,Rockbridge,Staunton,Lexington,-79.450178,37.713655
2,3,85,{D966D639-1944-4973-AC57-AD782BCA5F38},5/18/2021 2:23:35 PM,2021-05-18,2021,May,5,Tuesday,3,18,NaN,Groundhog,I-81S,Rockbridge,Staunton,Lexington,-79.448655,37.714697
3,4,86,{7F5EA06A-C97D-4947-8E9E-AA5A14CA919F},5/18/2021 2:52:00 PM,2021-05-18,2021,May,5,Tuesday,3,18,Deer,NaN,I-81S,Rockbridge,Staunton,Lexington,-79.561258,37.641463
4,5,88,{2706BA75-9F2C-49A6-8EEE-A7A4D02B42F1},5/18/2021 3:33:52 PM,2021-05-18,2021,May,5,Tuesday,3,18,Deer,NaN,I-81N,Rockbridge,Staunton,Lexington,-79.408782,37.758094

In [115]:
# compare the two dataframes by the ObjetID column to see if there are any that are not in both dataframes
Wildlifecarcass['ObjectID'].isin(VDOTcarcass['ObjectID'])
# Print the ones that are not in both dataframes
Wildlifecarcass[~Wildlifecarcass['ObjectID'].isin(VDOTcarcass['ObjectID'])]
# If there is are a lot of rows that are not present in the modified file, let's work with the original file

,ObjectID,GlobalID,Date and Pickup Time,Deer and Bear Removal,Other wildlife types,Route Name and Direction,Latitude_d,Longitude_d,County,District,Residency,x,y
68,192,5d78b070-397a-48be-b7a4-a3a813c72d70,6/11/2021 12:51:29 PM,Deer,NaN,NaN,NaN,NaN,Allenghany,Staunton,Lexington,-80.068247,37.812011
69,193,f4304959-a921-4f2b-89be-256e1ce212c4,6/11/2021 6:16:03 PM,NaN,Bird,NaN,NaN,NaN,Allenghany,Staunton,Lexington,-80.006811,37.781059
76,205,73468904-2aaf-4a92-9457-7088a16d312c,5/18/2021 12:47:21 PM,Bear,NaN,NaN,NaN,NaN,Rockbridge,Staunton,Lexington,-79.376002,37.836645
77,206,ce7c5e81-1870-4248-bfa1-d729d3ea284e,6/14/2021 12:56:05 PM,Deer,NaN,I-64E,NaN,NaN,Allenghany,Staunton,Lexington,-79.847447,37.811481
171,328,45bd4e5e-4410-4053-bba5-0e978877391a,7/13/2021 1:03:56 PM,Bear,NaN,I-64W,NaN,NaN,Augusta,Staunton,Harrisonburg,-78.978630,38.074964
281,447,ddb9c568-b28a-4078-8101-fc3a31f74af5,8/11/2021 1:05:54 PM,Deer,NaN,I-81S,NaN,NaN,Rockbridge,Staunton,Lexington,-79.412327,37.753490
2785,3459,e122cdb6-3cf1-4e9b-8782-8131fed80c12,8/30/2024 2:43:01 PM,Deer,NaN,NaN,37.714214,-79.448981,Rockbridge County,Staunton,Lexington,-79.448981,37.714214
2786,3460,723351c6-ec25-4aeb-9fc3-8f4cd76c60d8,8/30/2024 4:49:07 PM,Deer,NaN,NaN,38.018182,-78.442189,NaN,NaN,NaN,-78.442189,38.018182
2787,3461,f5a97e1b-c4ab-43ed-942d-350a931c0265,8/30/2024 4:56:42 PM,Bear,NaN,NaN,38.008095,-78.514471,NaN,NaN,NaN,-78.514471,38.008095
2788,3462,847d2699-1f21-4cba-ab4d-01e50025f56a,8/30/2024 5:11:01 PM,Deer,NaN,NaN,38.044587,-78.725023,NaN,NaN,NaN,-78.725023,38.044587
2789,3463,6b1749f8-3480-4032-b80b-354b5c90a03e,9/1/2024 9:23:44 PM,Bear,NaN,NaN,37.800136,-79.732983,Alleghany County,Staunton,Lexington,-79.732983,37.800136
2790,3464,241c0cb2-5ef4-4897-b9e6-fd66802d5ec1,9/3/2024 4:30:09 PM,Deer,NaN,NaN,37.830797,-79.757039,Alleghany County,Staunton,Lexington,-79.757039,37.830797
2791,3465,b25213d0-582a-4f01-b034-4be3df2fc35a,9/4/2024 5:37:48 PM,Deer,NaN,NaN,37.990524,-78.244015,NaN,NaN,NaN,-78.244015,37.990524
2792,3466,b89ffc13-a698-4ca5-8c76-a64118040723,9/5/2024 3:00:23 PM,Deer,NaN,NaN,37.678634,-79.496933,Rockbridge County,Staunton,Lexington,-79.496933,37.678634
2793,3467,67b18ebf-e049-4f58-9f09-bd8bcbe3bdd5,9/6/2024 12:40:58 PM,Deer,NaN,NaN,37.776826,-79.971086,Alleghany County,Staunton,Lexington,-79.971086,37.776826
2794,3468,f9717ca4-d775-422c-832c-168d9547efc0,9/6/2024 2:01:28 PM,Bear,NaN,NaN,37.793820,-80.043261,Alleghany County,Staunton,Lexington,-80.043261,37.793820
2795,3469,34be1656-1398-4d02-83e0-892aceb94864,9/6/2024 4:03:37 PM,Deer,NaN,NaN,38.069107,-78.699855,NaN,NaN,NaN,-78.699855,38.069107
2796,3470,39bd6f47-a568-4ab0-80b2-e53fc9d2d750,9/6/2024 4:05:04 PM,Bear,NaN,NaN,38.032942,-78.916142,NaN,NaN,NaN,-78.916142,38.032942
2797,3471,e2fd26cb-4f8a-45e4-8667-8ecca653caa6,9/6/2024 4:06:42 PM,Other,Skunk,NaN,37.989607,-78.740166,NaN,NaN,NaN,-78.740166,37.989607
2798,3472,c598e76f-ff4d-4d62-9322-4fc9b812cccd,9/6/2024 8:41:30 PM,Deer,NaN,NaN,38.017683,-78.447136,NaN,NaN,NaN,-78.447136,38.017683
2799,3473,e474187a-e660-4580-ab06-c5508ea620be,9/9/2024 11:45:39 AM,Deer,NaN,NaN,37.774200,-79.995484,Alleghany County,Staunton,Lexington,-79.995484,37.774200
2800,3474,2cdef455-2e74-4d83-b875-f26f2c3d15c3,9/9/2024 4:27:22 PM,Bear,NaN,NaN,37.782963,-80.009803,Alleghany County,Staunton,Lexington,-80.009803,37.782963
2801,3475,cc90ab88-12a9-4cce-a410-4e68e3d1fc81,9/10/2024 12:55:08 PM,Deer,NaN,NaN,37.847906,-79.468933,Rockbridge County,Staunton,Lexington,-79.468933,37.847906
2802,3476,d345f05a-86de-49f8-9e6f-3417d15dea8c,9/10/2024 5:40:48 PM,Deer,NaN,NaN,38.043762,-78.811799,NaN,NaN,NaN,-78.811799,38.043762

In [116]:
# Decision made to work with the original file

## Merge the 'Other wildlife types' col with the 'Deer and Bear Removal' column

In [117]:
# identify when the 'deer and bear removal column is NaN
# Wildlifecarcass['Deer and Bear Removal'].isna()
# identify when the 'deer and bear removal column is 'other'
# Wildlifecarcass['Deer and Bear Removal'] == 'Other'
# make a new column named 'wildlife'
Wildlifecarcass['wildlife'] = Wildlifecarcass['Deer and Bear Removal']

In [118]:
# What are the unique values in the 'wildlife' column?
Wildlifecarcass['wildlife'].unique()

array(['Deer', nan, 'Bear', 'Other', 'Notfound'], dtype=object)

In [119]:
# for the rows where the 'wildlife' column is in Nan, 'Other', 'Notfound' fill it with the value from the 'Other wildlife types' column
Wildlifecarcass.loc[Wildlifecarcass['wildlife'].isin([np.nan, 'Other', 'Notfound']), 'wildlife'] = Wildlifecarcass['Other wildlife types']

In [120]:
# Check what the unique species values are in the new 'wildlife' column
Wildlifecarcass['wildlife'].unique()

array(['Deer', 'Coyote', 'Groundhog', 'Skunk', 'Bear', 'Raccoon',
       'Otheranimal', 'Dog', 'Opossum', 'Bird', 'Cat', 'Otheranimal,Bird',
       'Fox', nan, 'Bobcat', 'Farmanimal', 'Squirrel', 'Turtle'],
      dtype=object)

In [121]:
# we find that the following values are questionable and warrent further investigation
wildlife_values_to_check = ['Otheranimal', 'Otheranimal,Bird', 'Farmanimal', 'Other', 'Notfound', np.nan]
# print rows from the dataframe where the 'wildlife' column is in the list of values to check
Wildlifecarcass[Wildlifecarcass['wildlife'].isin(wildlife_values_to_check)]

,ObjectID,GlobalID,Date and Pickup Time,Deer and Bear Removal,Other wildlife types,Route Name and Direction,Latitude_d,Longitude_d,County,District,Residency,x,y,wildlife
24,114,7846beb8-0768-4160-bcf1-3094b8213944,5/25/2021 1:55:34 PM,NaN,Otheranimal,I-81N,38.241979,-78.961527,Augusta,Staunton,Harrisonburg,-78.961527,38.241979,Otheranimal
86,215,543e8b37-b75a-4d6f-ad06-48e837ef7ce6,6/21/2021 4:03:20 PM,NaN,Otheranimal,I-81N,37.973772,-79.189059,Augusta,Staunton,Harrisonburg,-79.189059,37.973772,Otheranimal
88,217,83275414-53c9-4bf4-b0f3-d367871ddeb9,6/21/2021 5:23:51 PM,NaN,Otheranimal,I-81N,37.664289,-79.519778,Rockbridge,Staunton,Lexington,-79.519778,37.664289,Otheranimal
106,257,4f812eac-373c-4c68-84c1-fd036a0ff582,6/25/2021 6:48:05 PM,NaN,"Otheranimal,Bird",I-64W,38.031154,-78.596384,Albemarle,Culpeper,Charlottesville,-78.596384,38.031154,"Otheranimal,Bird"
204,362,b002c3da-d8a9-4a41-9e85-a68c6868524b,7/21/2021 6:45:15 PM,NaN,Otheranimal,I-81N,39.250782,-78.105115,Frederick,Staunton,Edinburg,-78.105115,39.250782,Otheranimal
226,384,4f98c27c-b857-4473-98ee-3121baf3b83f,7/26/2021 7:41:24 PM,NaN,Otheranimal,I-66w,39.011794,-78.328908,Shenandoah,Staunton,Edinburg,-78.328908,39.011794,Otheranimal
240,398,a0235fce-8b8c-4e0b-bf5f-9c3dbb0dc3fd,7/28/2021 6:19:39 PM,NaN,Otheranimal,I—66 W,38.896552,-77.914484,Fauguier,Culpeper,Warrenton,-77.914484,38.896552,Otheranimal
253,417,8182bc4e-365f-4083-855f-7a4c104a6939,8/2/2021 2:38:14 PM,NaN,NaN,NaN,38.035827,-78.696457,Albemarle,Culpeper,Charlottesville,-78.696457,38.035827,NaN
283,449,56e77acb-d4bf-4f91-a2bb-669e4a8b9ff3,8/12/2021 12:38:11 PM,NaN,Otheranimal,I-64E,38.013576,-78.467338,Albemarle,Culpeper,Charlottesville,-78.467338,38.013576,Otheranimal
291,480,03062749-5e4f-4de3-9dce-1be0fab7c402,8/18/2021 4:48:39 PM,NaN,Otheranimal,I-81S,38.002394,-79.173351,Augusta,Staunton,Harrisonburg,-79.173351,38.002394,Otheranimal
292,485,31eb6d5c-1a7f-436c-aa61-8917abf28917,8/20/2021 3:30:38 PM,NaN,Otheranimal,I-81S,37.659370,-79.532859,Rockbridge,Staunton,Lexington,-79.532859,37.659370,Otheranimal
293,486,706ee27b-90d7-408b-ab80-57c7becadd1b,8/22/2021 12:49:12 PM,NaN,Otheranimal,WEST,37.804207,-80.056007,Allenghany,Staunton,Lexington,-80.056007,37.804207,Otheranimal
320,528,c540857d-ef8e-415a-8e44-5846edcd5362,9/12/2021 12:11:30 AM,NaN,NaN,NaN,38.044491,-78.795967,Albemarle,Culpeper,Charlottesville,-78.795967,38.044491,NaN
329,539,457e5264-d233-4317-985d-5bbfe8331559,9/15/2021 2:04:48 PM,NaN,Otheranimal,I-64E,37.878406,-79.540608,Rockbridge,Staunton,Lexington,-79.540608,37.878406,Otheranimal
337,561,c2dd948a-9982-4528-a06b-fbd062ace03d,9/23/2021 7:27:07 PM,NaN,NaN,NaN,38.016245,-78.456448,Albemarle,Culpeper,Charlottesville,-78.456448,38.016245,NaN
367,608,0e22f0d2-146f-452b-afe1-65da2ad3a822,10/1/2021 6:19:14 PM,NaN,NaN,NaN,37.894992,-79.568212,Rockbridge,Staunton,Lexington,-79.568212,37.894992,NaN
379,621,24b31e35-2916-4767-b8f9-ca9ccfea6bca,10/8/2021 3:31:39 PM,NaN,Farmanimal,NaN,38.041374,-78.896930,Augusta,Staunton,Harrisonburg,-78.896930,38.041374,Farmanimal
450,693,1274cd6f-e2e8-4422-922e-6192c241e3ad,10/22/2021 6:26:53 PM,NaN,NaN,I-81N,37.756371,-79.408401,Rockbridge,Staunton,Lexington,-79.408401,37.756371,NaN
746,1268,ed3d9591-1b50-4fe3-b93e-bf5cdeff8973,10/20/2022 3:09:53 PM,Other,Farmanimal,I-66E,38.849080,-77.789351,Fauguier,Culpeper,Warrenton,-77.789351,38.849080,Farmanimal
1199,1738,eaebad23-d5b3-41fa-8624-d4a8b968fbe4,12/10/2022 2:12:09 PM,Other,NaN,I-81S,38.265971,-78.939762,Augusta County,Staunton,Harrisonburg,-78.939762,38.265971,NaN
1407,1950,40644124-ad51-4960-a07e-61e13da29ccf,3/28/2023 6:48:43 PM,Other,Otheranimal,I-64W,37.788903,-80.032120,Alleghany County,Staunton,Lexington,-80.032120,37.788903,Otheranimal
1419,1962,e433b742-700c-48bf-b2c5-f0e14d9f6f3c,4/6/2023 1:56:00 PM,Other,NaN,I-64E,37.772054,-79.948319,Alleghany County,Staunton,Lexington,-79.948319,37.772054,NaN
1918,2462,536a1b01-0f5f-4884-9cf7-c43e3a40cde9,11/2/2023 3:00:24 PM,Other,Otheranimal,NaN,37.656577,-79.539387,Rockbridge County,Staunton,Lexington,-79.539387,37.656577,Otheranimal
2233,2777,7cd6c0fe-0742-4ee8-82a5-860e6fae0b1b,11/27/2023 5:15:40 PM,Notfound,NaN,NaN,37.748596,-79.416294,Rockbridge County,Staunton,Lexington,-79.416294,37.748596,NaN
2377,2996,d1129f77-b469-4ee2-83a1-ff878f7da857,1/11/2024 9:05:48 PM,Other,Otheranimal,NaN,37.307027,-77.395394,Chesterfield County,Richmond,Chesterfield,-77.395394,37.307027,Otheranimal
2386,3053,a9d7a38e-6a10-4929-84bc-2e4e5e6ce9a1,1/16/2024 4:09:02 PM,NaN,NaN,NaN,37.604000,-77.617500,NaN,NaN,NaN,-77.617500,37.604000,NaN
2502,3172,7d9f1aa9-2e2b-4e3d-898a-41840d594651,4/4/2024 6:17:01 PM,Other,Farmanimal,NaN,37.654069,-77.542225,City of Charlottesville,Culpeper,Louisa,-77.542225,37.654069,Farmanimal
2514,3184,c276c3fd-4a8d-4b0d-9e96-0e948a110426,4/22/2024 3:20:53 PM,Other,Otheranimal,NaN,37.645497,-79.556587,Rockbridge County,Staunton,Lexington,-79.556587,37.645497,Otheranimal
2761,3434,af84cdcf-77a8-4839-b9a1-ff59ee9751df,8/21/2024 3:06:20 PM,NaN,NaN,NaN,38.227265,-78.978634,NaN,NaN,NaN,-78.978634,38.227265,NaN
2763,3436,71ed7d97-9c0f-40eb-bd3f-67ea8b18072c,8/21/2024 3:28:46 PM,NaN,NaN,NaN,38.224887,-78.981138,NaN,NaN,NaN,-78.981138,38.224887,NaN

In [122]:
# We drop these rows from the dataframe, after inspection it is clear that there is no way to determine species for these rows
Wildlifecarcass = Wildlifecarcass.drop(Wildlifecarcass[Wildlifecarcass['wildlife'].isin(wildlife_values_to_check)].index)

In [123]:
Wildlifecarcass.value_counts('wildlife')

wildlife
Deer         2363
Bear          196
Coyote         56
Raccoon        49
Dog            19
Fox            18
Opossum        18
Bird           12
Groundhog      11
Cat             9
Bobcat          8
Skunk           7
Squirrel        5
Turtle          2
Name: count, dtype: int64

## Inspect rows that have NaN Values

## Work on standardizing the road strings

In [124]:
#inspect the data frames 
VDOTcarcass.head()

,fid,ObjectID,GlobalID,StartTime,Date,Year,MonthName,MonthNumber,DOWName,DOWNumber,DOMNumber,Wildlife,WildlifeOther,Route,Jurisdiction,District,Residency,x,y
0,1,83,{AC10868C-9C94-444F-BB95-36B03BFD84A0},5/18/2021 12:43:01 PM,2021-05-18,2021,May,5,Tuesday,3,18,Deer,NaN,I-81S,Rockbridge,Staunton,Lexington,-79.370354,37.835462
1,2,84,{F529067B-0A14-401A-B0F7-B1701E771F4A},5/18/2021 2:15:55 PM,2021-05-18,2021,May,5,Tuesday,3,18,NaN,Coyote,I-81S,Rockbridge,Staunton,Lexington,-79.450178,37.713655
2,3,85,{D966D639-1944-4973-AC57-AD782BCA5F38},5/18/2021 2:23:35 PM,2021-05-18,2021,May,5,Tuesday,3,18,NaN,Groundhog,I-81S,Rockbridge,Staunton,Lexington,-79.448655,37.714697
3,4,86,{7F5EA06A-C97D-4947-8E9E-AA5A14CA919F},5/18/2021 2:52:00 PM,2021-05-18,2021,May,5,Tuesday,3,18,Deer,NaN,I-81S,Rockbridge,Staunton,Lexington,-79.561258,37.641463
4,5,88,{2706BA75-9F2C-49A6-8EEE-A7A4D02B42F1},5/18/2021 3:33:52 PM,2021-05-18,2021,May,5,Tuesday,3,18,Deer,NaN,I-81N,Rockbridge,Staunton,Lexington,-79.408782,37.758094

In [125]:
# Find the names for the routes
VDOTcarcass['Route'].unique()

array(['I-81S', 'I-81N', 'I-64E', 'I-64W', nan, 'I-64 E', 'I 64E',
       'I-64 W', 'I 64 w', 'I-81 w', 'I 66 east', 'I-66 east', 'I-81 N',
       'I81 N', 'I-66 W', 'I-66E', 'I-81 S', 'I-66 west', 'I-66 WB',
       'I-66 EB', 'I-66 E', 'I-66w', 'I-81 W', '1-81 W', 'I66 E',
       'I—66 W', 'I-64 east', '64w', 'I-66', 'I66', 'W', 'I64w', 'WEST',
       'I64E', 'EAST', '64E', 'WBRS', 'I64EB', 'I64W', 'I-64EAST',
       'I-64WEST', 'I64WESTB', 'I-66W', 'I-81s'], dtype=object)

In [154]:
import re

In [156]:
# Standardize the Route Name
VDOTcarcass['Route'] = VDOTcarcass['Route'].str.upper()
VDOTcarcass['Route'] = VDOTcarcass['Route'].str.replace(r'\s+', '', regex=True)
VDOTcarcass['Route'] = VDOTcarcass['Route'].str.replace(r'[^I0-9-]', '', regex=True)

# Function to standardize routes
def standardize_route(route):
    if isinstance(route, str) and route:  # Check if the input is a non-empty string
        # Handle specific case for '1-<number>'
        if re.match(r'1-(\d+)', route):
            return f'I-{route.split("-")[1]}'
        
        # Handle cases like I-<number>, I<number>, and <number>
        match = re.match(r'^(I-?(\d+)|(\d+))$', route)  # Matches I-<number>, I<number>, or <number>
        if match:
            # Return as I-<number>
            return f'I-{match.group(2) or match.group(3)}'
    
    return np.nan  # Return NaN for non-string inputs or unmatched patterns

# Apply the standardization function
VDOTcarcass['Standardized route'] = VDOTcarcass['Route'].apply(standardize_route)

In [157]:
# I want to double check to see if any originial routes got mislabled as NaN
mask = VDOTcarcass['Route'].notna() & VDOTcarcass['Standardized route'].isna()
result = VDOTcarcass[mask]
result

,fid,ObjectID,GlobalID,StartTime,Date,Year,MonthName,MonthNumber,DOWName,DOWNumber,DOMNumber,Wildlife,WildlifeOther,Route,Jurisdiction,District,Residency,Longitude,Latitude,Standardized route
267,268,436,{5479E03B-2D7D-4EBC-A42B-E3BE29165DED},8/9/2021 2:11:42 PM,2021-08-09,2021,August,8,Monday,2,9,NaN,Skunk,,Rockbridge,Staunton,Lexington,-79.406252,37.797377,NaN
287,288,486,{706EE27B-90D7-408B-AB80-57C7BECADD1B},8/22/2021 12:49:12 PM,2021-08-22,2021,August,8,Sunday,1,22,NaN,Otheranimal,,Allenghany,Staunton,Lexington,-80.056007,37.804207,NaN
302,303,508,{A81FE89F-ECCB-40BA-A561-5E9BE733A5FC},9/2/2021 1:50:37 PM,2021-09-02,2021,September,9,Thursday,5,2,Deer,NaN,,Rockbridge,Staunton,Lexington,-79.444626,37.832944,NaN
315,316,529,{6F4AD04E-B2FA-44E9-9B56-BD2B763F924E},9/13/2021 1:11:30 PM,2021-09-13,2021,September,9,Monday,2,13,Deer,NaN,,Fauguier,Culpeper,Warrenton,-77.843565,38.858630,NaN
326,327,542,{5912F711-8A5A-417F-8958-2035C927D088},9/16/2021 8:27:54 PM,2021-09-16,2021,September,9,Thursday,5,16,NaN,Coyote,,Allenghany,Staunton,Lexington,-79.741659,37.817340,NaN

In [158]:
# Checking count of values 
VDOTcarcass['Standardized route'].value_counts(dropna = False)

Standardized route
I-64    1110
NaN      963
I-81     419
I-66     287
Name: count, dtype: int64

In [134]:
Wildlifecarcass.head()

,ObjectID,GlobalID,Date and Pickup Time,Deer and Bear Removal,Other wildlife types,Route Name and Direction,Latitude_d,Longitude_d,County,District,Residency,x,y,wildlife
0,83,ac10868c-9c94-444f-bb95-36b03bfd84a0,5/18/2021 12:43:01 PM,Deer,NaN,I-81S,37.835462,-79.370354,Rockbridge,Staunton,Lexington,-79.370354,37.835462,Deer
1,84,f529067b-0a14-401a-b0f7-b1701e771f4a,5/18/2021 2:15:55 PM,NaN,Coyote,I-81S,37.713655,-79.450178,Rockbridge,Staunton,Lexington,-79.450178,37.713655,Coyote
2,85,d966d639-1944-4973-ac57-ad782bca5f38,5/18/2021 2:23:35 PM,NaN,Groundhog,I-81S,37.714697,-79.448655,Rockbridge,Staunton,Lexington,-79.448655,37.714697,Groundhog
3,86,7f5ea06a-c97d-4947-8e9e-aa5a14ca919f,5/18/2021 2:52:00 PM,Deer,NaN,I-81S,37.641463,-79.561258,Rockbridge,Staunton,Lexington,-79.561258,37.641463,Deer
4,88,2706ba75-9f2c-49a6-8eee-a7a4d02b42f1,5/18/2021 3:33:52 PM,Deer,NaN,I-81N,37.758094,-79.408782,Rockbridge,Staunton,Lexington,-79.408782,37.758094,Deer

In [159]:
# Checking unique values to see what transformations need to be made
Wildlifecarcass['Route Name and Direction'].unique()

array(['I-81S', 'I-81N', 'I-64E', 'I-64W', nan, 'I-64 E', 'I 64E',
       'I-64 W', 'I 64 w', 'I-81 w', 'I 66 east', 'I-66 east', 'I-81 N',
       'I81 N', 'I-66 W', 'I-66E', 'I-81 S', 'I-66 west', 'I-66 WB ',
       'I-66 EB', 'I-66 E', 'I-66w', 'I-81 W', '1-81 W', 'I66 E',
       'I-64 east ', '64w', 'I-66', 'I66', 'I-66 ', 'W', 'I64w', 'I64E',
       'EAST', '64E', 'WBRS', 'I64EB', 'I64W', 'I-64EAST', 'I-64WEST',
       'I64WESTB', 'I-66W', 'I-81s'], dtype=object)

In [177]:
# Double check WBRS and W and not getting result 
Wildlifecarcass[Wildlifecarcass['Route Name and Direction'].str.contains('WBRS', na=False)]

Empty DataFrame
Columns: [ObjectID, GlobalID, Date and Pickup Time, Deer and Bear Removal, Other wildlife types, Route Name and Direction, Latitude_d, Longitude_d, County, District, Residency, x, y, wildlife, Standardized route]
Index: []

In [160]:
# Standardize the Route Name
Wildlifecarcass['Route Name and Direction'] = Wildlifecarcass['Route Name and Direction'].str.upper()  
Wildlifecarcass['Route Name and Direction'] = Wildlifecarcass['Route Name and Direction'].str.replace(r'\s+', '', regex=True) 
Wildlifecarcass['Route Name and Direction'] = Wildlifecarcass['Route Name and Direction'].str.replace(r'[^I0-9-]', '', regex=True)

# Function to standardize routes
def standardize_route(route):
    if isinstance(route, str) and route:  # Check if the input is a non-empty string
        # Handle specific case for '1-<number>'
        if re.match(r'1-(\d+)', route):
            return f'I-{route.split("-")[1]}'
        
        # Handle cases like I-<number>, I<number>, and <number>
        match = re.match(r'^(I-?(\d+)|(\d+))$', route)  # Matches I-<number>, I<number>, or <number>
        if match:
            # Return as I-<number>
            return f'I-{match.group(2) or match.group(3)}'
    
    return np.nan  # Return NaN for non-string inputs or unmatched patterns

# Apply the standardization function
Wildlifecarcass['Standardized route'] = Wildlifecarcass['Route Name and Direction'].apply(standardize_route)

In [161]:
# Double check to see if I lost any routes 
mask = Wildlifecarcass['Route Name and Direction'].notna() & Wildlifecarcass['Standardized route'].isna()
result = Wildlifecarcass[mask]
result

,ObjectID,GlobalID,Date and Pickup Time,Deer and Bear Removal,Other wildlife types,Route Name and Direction,Latitude_d,Longitude_d,County,District,Residency,x,y,wildlife,Standardized route
272,436,5479e03b-2d7d-4ebc-a42b-e3be29165ded,8/9/2021 2:11:42 PM,NaN,Skunk,,37.797377,-79.406252,Rockbridge,Staunton,Lexington,-79.406252,37.797377,Skunk,NaN
308,508,a81fe89f-eccb-40ba-a561-5e9be733a5fc,9/2/2021 1:50:37 PM,Deer,NaN,,37.832944,-79.444626,Rockbridge,Staunton,Lexington,-79.444626,37.832944,Deer,NaN
321,529,6f4ad04e-b2fa-44e9-9b56-bd2b763f924e,9/13/2021 1:11:30 PM,Deer,NaN,,38.858630,-77.843565,Fauguier,Culpeper,Warrenton,-77.843565,38.858630,Deer,NaN
332,542,5912f711-8a5a-417f-8958-2035c927d088,9/16/2021 8:27:54 PM,NaN,Coyote,,37.817340,-79.741659,Allenghany,Staunton,Lexington,-79.741659,37.817340,Coyote,NaN

In [162]:
# Counting up the routes, NaN is the second highest 
Wildlifecarcass['Standardized route'].value_counts(dropna = False)

Standardized route
I-64    1107
NaN      970
I-81     412
I-66     284
Name: count, dtype: int64

In [178]:
# Um...can someone please double check this 
Wildlifecarcass[Wildlifecarcass['Route Name and Direction'].str.contains('WBRS', na=False)]

Empty DataFrame
Columns: [ObjectID, GlobalID, Date and Pickup Time, Deer and Bear Removal, Other wildlife types, Route Name and Direction, Latitude_d, Longitude_d, County, District, Residency, x, y, wildlife, Standardized route]
Index: []