In [2]:
import pandas as pd
import numpy as np

In [3]:
VDOTcarcass = pd.read_csv('VDOTCarcass.csv') 
Wildlifecarcass = pd.read_csv('Wildlife_Carcass_Removal_Tracking_5676419084963296149.csv')

In [4]:
VDOTcarcass

,fid,ObjectID,GlobalID,StartTime,Date,Year,MonthName,MonthNumber,DOWName,DOWNumber,DOMNumber,Wildlife,WildlifeOther,Route,Jurisdiction,District,Residency,x,y
0,1,83,{AC10868C-9C94-444F-BB95-36B03BFD84A0},5/18/2021 12:43:01 PM,2021-05-18,2021,May,5,Tuesday,3,18,Deer,NaN,I-81S,Rockbridge,Staunton,Lexington,-79.370354,37.835462
1,2,84,{F529067B-0A14-401A-B0F7-B1701E771F4A},5/18/2021 2:15:55 PM,2021-05-18,2021,May,5,Tuesday,3,18,NaN,Coyote,I-81S,Rockbridge,Staunton,Lexington,-79.450178,37.713655
2,3,85,{D966D639-1944-4973-AC57-AD782BCA5F38},5/18/2021 2:23:35 PM,2021-05-18,2021,May,5,Tuesday,3,18,NaN,Groundhog,I-81S,Rockbridge,Staunton,Lexington,-79.448655,37.714697
3,4,86,{7F5EA06A-C97D-4947-8E9E-AA5A14CA919F},5/18/2021 2:52:00 PM,2021-05-18,2021,May,5,Tuesday,3,18,Deer,NaN,I-81S,Rockbridge,Staunton,Lexington,-79.561258,37.641463
4,5,88,{2706BA75-9F2C-49A6-8EEE-A7A4D02B42F1},5/18/2021 3:33:52 PM,2021-05-18,2021,May,5,Tuesday,3,18,Deer,NaN,I-81N,Rockbridge,Staunton,Lexington,-79.408782,37.758094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2774,2775,3453,{60E3420F-BDF3-46A0-90B6-8EF18F88211A},8/29/2024 2:59:18 PM,2024-08-29,2024,August,8,Thursday,5,29,Other,Raccoon,NaN,Rockbridge County,Staunton,Lexington,-79.464858,37.702692
2775,2776,3455,{7EF437E0-D3AF-45D7-8BE6-C33C7EE54665},8/29/2024 5:23:40 PM,2024-08-29,2024,August,8,Thursday,5,29,Deer,NaN,NaN,NaN,NaN,NaN,-77.845281,38.857687
2776,2777,3456,{24E24BCC-3EBE-4938-A43E-33A13791F1E0},8/29/2024 6:10:55 PM,2024-08-29,2024,August,8,Thursday,5,29,Other,Turtle,NaN,NaN,NaN,NaN,-77.291924,37.532378
2777,2778,3457,{24E503B3-6B7F-4D3B-B192-052E3EAAC398},8/29/2024 6:23:58 PM,2024-08-29,2024,August,8,Thursday,5,29,Deer,NaN,NaN,NaN,NaN,NaN,-77.279497,37.554617
2778,2779,3458,{D53D74C2-57BB-44BA-8169-FC67734DA92B},8/29/2024 6:37:43 PM,2024-08-29,2024,August,8,Thursday,5,29,Bear,NaN,NaN,NaN,NaN,NaN,-77.289240,37.532410

In [5]:
Wildlifecarcass

,ObjectID,GlobalID,Date and Pickup Time,Deer and Bear Removal,Other wildlife types,Route Name and Direction,Latitude_d,Longitude_d,County,District,Residency,x,y
0,83,ac10868c-9c94-444f-bb95-36b03bfd84a0,5/18/2021 12:43:01 PM,Deer,NaN,I-81S,37.835462,-79.370354,Rockbridge,Staunton,Lexington,-79.370354,37.835462
1,84,f529067b-0a14-401a-b0f7-b1701e771f4a,5/18/2021 2:15:55 PM,NaN,Coyote,I-81S,37.713655,-79.450178,Rockbridge,Staunton,Lexington,-79.450178,37.713655
2,85,d966d639-1944-4973-ac57-ad782bca5f38,5/18/2021 2:23:35 PM,NaN,Groundhog,I-81S,37.714697,-79.448655,Rockbridge,Staunton,Lexington,-79.448655,37.714697
3,86,7f5ea06a-c97d-4947-8e9e-aa5a14ca919f,5/18/2021 2:52:00 PM,Deer,NaN,I-81S,37.641463,-79.561258,Rockbridge,Staunton,Lexington,-79.561258,37.641463
4,88,2706ba75-9f2c-49a6-8eee-a7a4d02b42f1,5/18/2021 3:33:52 PM,Deer,NaN,I-81N,37.758094,-79.408782,Rockbridge,Staunton,Lexington,-79.408782,37.758094
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2798,3472,c598e76f-ff4d-4d62-9322-4fc9b812cccd,9/6/2024 8:41:30 PM,Deer,NaN,NaN,38.017683,-78.447136,NaN,NaN,NaN,-78.447136,38.017683
2799,3473,e474187a-e660-4580-ab06-c5508ea620be,9/9/2024 11:45:39 AM,Deer,NaN,NaN,37.774200,-79.995484,Alleghany County,Staunton,Lexington,-79.995484,37.774200
2800,3474,2cdef455-2e74-4d83-b875-f26f2c3d15c3,9/9/2024 4:27:22 PM,Bear,NaN,NaN,37.782963,-80.009803,Alleghany County,Staunton,Lexington,-80.009803,37.782963
2801,3475,cc90ab88-12a9-4cce-a410-4e68e3d1fc81,9/10/2024 12:55:08 PM,Deer,NaN,NaN,37.847906,-79.468933,Rockbridge County,Staunton,Lexington,-79.468933,37.847906
2802,3476,d345f05a-86de-49f8-9e6f-3417d15dea8c,9/10/2024 5:40:48 PM,Deer,NaN,NaN,38.043762,-78.811799,NaN,NaN,NaN,-78.811799,38.043762

In [6]:
Wildlifecarcass = Wildlifecarcass.rename(columns={'Other wildlife types': 'WildlifeOther'})

In [7]:
merged_df = pd.merge(VDOTcarcass, Wildlifecarcass, on='WildlifeOther', how='outer', indicator=True)

In [10]:
no_match_df1 = merged_df[merged_df['WildlifeOther'] == 'left_only']

In [11]:
no_match_df2 = merged_df[merged_df['WildlifeOther'] == 'right_only']

In [ ]:
merged_df

,fid,ObjectID_x,GlobalID_x,StartTime,Date,Year,MonthName,MonthNumber,DOWName,DOWNumber,...,Deer and Bear Removal,Route Name and Direction,Latitude_d,Longitude_d,County,District_y,Residency_y,x_y,y_y,_merge
0,1,83,{AC10868C-9C94-444F-BB95-36B03BFD84A0},5/18/2021 12:43:01 PM,2021-05-18,2021,May,5,Tuesday,3,...,Deer,I-81S,37.835462,-79.370354,Rockbridge,Staunton,Lexington,-79.370354,37.835462,both
1,1,83,{AC10868C-9C94-444F-BB95-36B03BFD84A0},5/18/2021 12:43:01 PM,2021-05-18,2021,May,5,Tuesday,3,...,Deer,I-81S,37.641463,-79.561258,Rockbridge,Staunton,Lexington,-79.561258,37.641463,both
2,1,83,{AC10868C-9C94-444F-BB95-36B03BFD84A0},5/18/2021 12:43:01 PM,2021-05-18,2021,May,5,Tuesday,3,...,Deer,I-81N,37.758094,-79.408782,Rockbridge,Staunton,Lexington,-79.408782,37.758094,both
3,1,83,{AC10868C-9C94-444F-BB95-36B03BFD84A0},5/18/2021 12:43:01 PM,2021-05-18,2021,May,5,Tuesday,3,...,Deer,I-81N,37.783687,-79.400408,Rockbridge,Staunton,Lexington,-79.400408,37.783687,both
4,1,83,{AC10868C-9C94-444F-BB95-36B03BFD84A0},5/18/2021 12:43:01 PM,2021-05-18,2021,May,5,Tuesday,3,...,Deer,I-64E,37.777570,-80.002207,Allenghany,Staunton,Lexington,-80.002207,37.777570,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6550601,2437,3109,{0BF51F70-4E8E-4AEF-BE9C-780C70FD5582},2/7/2024 9:24:48 PM,2024-02-07,2024,February,2,Wednesday,4,...,Other,NaN,37.662713,-77.655069,NaN,NaN,NaN,-77.655069,37.662713,both
6550602,2685,3363,{6E966E67-6F53-48B7-B392-B0546DEFFDB9},7/10/2024 1:07:17 PM,2024-07-10,2024,July,7,Wednesday,4,...,Other,NaN,37.817079,-79.440995,NaN,NaN,NaN,-79.440995,37.817079,both
6550603,2685,3363,{6E966E67-6F53-48B7-B392-B0546DEFFDB9},7/10/2024 1:07:17 PM,2024-07-10,2024,July,7,Wednesday,4,...,Other,NaN,37.532378,-77.291924,NaN,NaN,NaN,-77.291924,37.532378,both
6550604,2777,3456,{24E24BCC-3EBE-4938-A43E-33A13791F1E0},8/29/2024 6:10:55 PM,2024-08-29,2024,August,8,Thursday,5,...,Other,NaN,37.817079,-79.440995,NaN,NaN,NaN,-79.440995,37.817079,both
6550605,2777,3456,{24E24BCC-3EBE-4938-A43E-33A13791F1E0},8/29/2024 6:10:55 PM,2024-08-29,2024,August,8,Thursday,5,...,Other,NaN,37.532378,-77.291924,NaN,NaN,NaN,-77.291924,37.532378,both

In [ ]:
merged_df.column

NameError: name 'merged_df' is not defined